@startuml
folder "Hello-Word" {
  folder "Docs" {
    folder "Architecture" {}
    folder "checklists" {}
  }
  file ".gitignore"
  file "package.json"
  file "vite.config.ts"
  file "index.html"
  file "tailwind.config.js"
  file "babel.config.js"
  folder "src" {
    folder "assets" {}
    folder "components" {}
    folder "core" {
      folder "hooks" {}
      folder "services" {}
      folder "types" {}
    }
    folder "hooks" {}
    folder "navigation" {}
    folder "platforms" {}
    folder "screens" {}
    folder "store" {}
    folder "types" {}
    folder "utils" {}
  }
}
@enduml
