%% Repo with src structure generated 2025-06-21
flowchart TD
  A[Hello-Word-c/]
  A --> Docs
  A --> src
  Docs --> Architecture
  Docs --> Planning
  Docs --> checklists
  src --> assets
  src --> components
  src --> core
  src --> hooks
  src --> navigation
  src --> platforms
  src --> screens
  src --> store
  src --> types
  src --> utils
