flowchart TD
  A[Hello-Word/]
  A --> B[Docs/]
  B --> C[Architecture/]
  B --> D[checklists/]
  A --> E[.gitignore]
  A --> F[package.json]
  A --> H[vite.config.ts]
  A --> I[index.html]
  A --> J[tailwind.config.js]
  A --> K[babel.config.js]
  A --> G[src/]
  G --> G1[assets/]
  G --> G2[components/]
  G --> G3[core/]
  G3 --> G3A[hooks/]
  G3 --> G3B[services/]
  G3 --> G3C[types/]
  G --> G4[hooks/]
  G --> G5[navigation/]
  G --> G6[platforms/]
  G --> G7[screens/]
  G --> G8[store/]
  G --> G9[types/]
  G --> G10[utils/]
